apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: skills-deploy-to-azure
  annotations:
    github.com/project-slug: Houssem-Azzouz/skills-deploy-to-azure
    backstage.io/kubernetes-id: deployment.apps/hello-minikube
  links:
    - url: https://asharq.com/
      title: Doc
spec:
  type: service
  lifecycle: unknown
  owner: user:default/houssem-azzouz
